name: quran_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_offline: ^4.0.0
  flutter_easyloading: ^3.0.5
  kiwi: ^5.0.1
  flutter_flavor: ^3.1.3
  flutter_pretty_dio_logger: ^3.0.0
  dio: ^5.7.0
  flutter_form_bloc: ^0.31.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  carousel_slider: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dependency_overrides:
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  kiwi_generator: ^4.2.1
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
